### ISSUE TITLE
allow useMoustaches.tokenize.custom(string, string) for custom moustaches

### ISSUE THREAD

**Issue by jhheider** [pkgxdev/libpkgx#52]
this would greatly simplify https://github.com/pkgxdev/brewkit/pull/196 which overloads version.raw to allow regexp rewriting in the URLs.

**Comment by mxcl** [comment]
can you provide the example of why thanks

**Comment by jhheider** [comment]
yeah... looking back at our exchange in discord, it was about the overloading of `version.raw` at https://github.com/pkgxdev/brewkit/pull/196/files#diff-4580bd7f95073ce9a8e3d00278a10fe7d2411d1e52d64132691b1a97350e1090R117-R139. that would allow for the definition of a `version.rewritten` key _in that sequence of code_ that wouldn't necessarily require explicit support in useMoustaches (beyond the generalized case of allowing custom moustache implementations). this means consumers of libpkgx (such as brewkit) could inject their own moustached keys using libpkgx primatives for their specific use-case.

**Comment by jhheider** [comment]
conversation begins [here](https://discord.com/channels/906608167901876256/1115922030420836432/1168666560408326298) if you want to slog through it.

**Comment by mxcl** [comment]
Closing since there are no explicit examples provided.
