### ISSUE TITLE
`libpkgx` sets `XDG_DATA_DIRS` in some cases

### ISSUE THREAD

**Issue by jhheider** [pkgxdev/libpkgx#70]
it appears that this interferes with the proper functioning of e.g. `gsettings` from GNOME. since tools use the standard-defined defaults *if the value is unset*, i think we need to consider that _if_ we add values to it, we must first add the standards-defined fallback to prevent changing behavior. see the below thread for an example of how it interfere's with GNOME's tooling.

              Oh. Maybe we have a bug in pkgx then?

```console 
❯ env | grep XDG
XDG_RUNTIME_DIR=/run/user/1002/

❯ pkgx env | grep XDG
XDG_DATA_DIRS=/home/felipecrs/.pkgx/gnu.org/coreutils/v9.5.0/share
XDG_RUNTIME_DIR=/run/user/1002/
```

If pkgx was not supposed to alter `XDG_` vars in runtime, then it was not supposed to inject `XDG_DATA_DIRS` either, I suppose.

_Originally posted by @felipecrs in https://github.com/pkgxdev/pantry/issues/5991#issuecomment-2081165688_

**Comment by mxcl** [comment]
Sounds right. What's the default?

**Comment by jhheider** [comment]
`If $XDG_DATA_DIRS is either not set or empty, a value equal to /usr/local/share/:/usr/share/ should be used.`

ref: https://specifications.freedesktop.org/basedir-spec/latest/index.html#variables
